language: php

sudo: false

php:
# Temporarily disabling testing different PHP versions for testing Travis CI.
# - 5.3
# - 5.4
- 5.5
# - 5.6
# - hhvm

env:
- WP_VERSION=latest WP_MULTISITE=0 TEMP=/tmp

install:
- test/install.sh -c test/settings.travis.cfg 
#- if [[ $TRAVIS_PHP_VERSION = '5.5' && $WP_VERSION = 'latest' && $WP_MULTISITE = '0'
#  ]]; then bash test/install.sh -c test/settings.travis.cfg; else bash test/install.sh -c test/settings.travis.cfg; fi
  
before_script:
  # starting PHP server (PHP 5.4)
  - php -S 127.0.0.1:4000 &
  - sleep 3
  
script:
# - bash test/run.sh -c test/settings.travis.cfg
- if [[ $TRAVIS_PHP_VERSION = '5.5' && $WP_VERSION = 'latest' && $WP_MULTISITE = '0'
  ]]; then bash test/run.sh -c test/settings.travis.cfg -l './_output/coverage.xml'; else bash test/run.sh -c test/settings.travis.cfg; fi

after_script:
- if [[ $TRAVIS_PHP_VERSION = '5.5' && $WP_VERSION = 'latest' && $WP_MULTISITE = '0'
  ]]; then wget https://scrutinizer-ci.com/ocular.phar --no-check-certificate; fi
- if [[ $TRAVIS_PHP_VERSION = '5.5' && $WP_VERSION = 'latest' && $WP_MULTISITE = '0'
  ]]; then php ocular.phar code-coverage:upload --format=php-clover './_output/coverage.xml';
  fi